version: "3.8"

services:
  labtrack-api:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: labtrack-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - labtrackdb
  labtrackdb:
    image: mysql:8.0
    container_name: labtrackdb
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}              
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data:
