version: "3.8"

services:
  labtrack-api:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: labtrack-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
